queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: >-
      automatic merge for  Dependabot pull requests
    conditions:
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - check-success=GitGuardian Security Checks
      - check-success=CodeQL
      - check-success=Build and Test (18.x)
      - check-success=Build and Test (14.x)
      - check-success=Build and Test (16.x)
    actions:
      label:
        add:
          - backend
      queue:
        name: default
        method: rebase
 