queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: >-
      automatic merge for backend Dependabot pull requests where there is no
      major version change
    conditions:
      - files~=^api/
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - 'title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.'
      - check-success=GitGuardian Security Checks
      - check-success=CodeQL
      - check-success=Build and Test (18.x)
      - check-success=Build and Test (14.x)
      - check-success=Build and Test (16.x)
    actions:
      label:
        add:
          - backend
      queue:
        name: default
        method: rebase
  - name: >-
      automatic merge for frontend Dependabot pull requests where there is no
      major version change
    conditions:
      - files~=^app/
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - 'title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.'
      - check-success=GitGuardian Security Checks
      - check-success=CodeQL
    actions:
      label:
        add:
          - frontend
      queue:
        name: default
        method: rebase
  - name: >-
      merge approved major version changes
    conditions:
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - check-success=GitGuardian Security Checks
      - check-success=CodeQL
      - approved-reviews-by=georgegebbett
    actions:
      label:
        add:
          - manually-approved
      queue:
        name: default
        method: rebase
  - name: >-
      ask for review on dependabot PRs where there is a major version change
    conditions:
      - 'author~=^dependabot(|-preview)\[bot\]$'
      - check-success=GitGuardian Security Checks
      - check-success=CodeQL
    actions:
      label:
        add:
          - dependancy-major-version
      request_reviews:
        users:
            - georgegebbett
