version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db_dev:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - type: bind
        source: ./api
        target: /api
    ports:
      - "4000:4000"
    depends_on:
      - "mongo"

volumes:
  mongo_db_dev:
