version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    command: mongod --port ${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-root}
    volumes:
      - mongo_db:/data/db
    ports:
      - "${MONGO_PORT:-27017}"

  backend:
    image: ghcr.io/georgegebbett/recipe-buddy-backend:latest
    environment:
      MONGO_USER: ${MONGO_USER:-root}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-root}
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
    depends_on:
      - "mongo"

  frontend:
    image: ghcr.io/georgegebbett/recipe-buddy-frontend:latest
    ports:
      - "${FRONTEND_PORT:-4000}:80"
    depends_on:
      - "backend"

volumes:
  mongo_db:
