name: 'Prepare'
description: 'Sets up the build for NodeJS and cache'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
