# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - api/**
  pull_request:
    branches:
      - master
      - develop
    paths:
      - api/**

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'api/yarn.lock'
    - run: yarn install --frozen-lockfile
    - run: npm run build --if-present
    - run: npm test
