name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-style:
    uses: ./.github/workflows/code-style.yml

  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/build-setup

      - name: Check
        run: pnpm check

  knip:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/build-setup

      - name: Check
        run: pnpm knip
